In [107]:
import numpy as np
import pandas as pd

In [108]:
#data reading and preprocessing
df_train = pd.read_csv('D:/Assignment_ML/sentiment_tweet/training_data.csv',encoding = "ISO-8859-1" )
#df_test = pd.read_csv('D:/Assignment_ML/sentiment_tweet/testdata.manual.2009.06.14.csv',encoding = "ISO-8859-1" )  
df =df_train

In [109]:
#df =df_train.append(df_test)
df.head()

,0,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, that's a bummer. You shoulda got David Carr of Third Day to do it. ;D"
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [110]:
df.head(5)
df.columns = ['polarity of tweet','tweet_id','date of tweet','query','user_id','tweet_text']
df.head()

,polarity of tweet,tweet_id,date of tweet,query,user_id,tweet_text
0,0,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
1,0,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
2,0,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
3,0,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
4,0,1467811372,Mon Apr 06 22:20:00 PDT 2009,NO_QUERY,joy_wolf,@Kwesidei not the whole crew

In [111]:
# data statistics
neg = len(df[df["polarity of tweet"] == 0])
pos = len(df[df["polarity of tweet"] == 4])
neu = len(df[df["polarity of tweet"] == 2])
print (neg, neu, pos, len(df))

799999 0 800000 1599999

In [112]:
noquery = len(df[df["query"] == "NO_QUERY"])
print(noquery)

1599999

In [113]:
df_test = pd.read_csv('D:/Assignment_ML/sentiment_tweet/testdata.manual.2009.06.14.csv',encoding = "ISO-8859-1" ) 
df_test.head()

,4,3,Mon May 11 03:17:40 UTC 2009,kindle2,tpryan,"@stellargirl I loooooooovvvvvveee my Kindle2. Not that the DX is cool, but the 2 is fantastic in its own right."
0,4,4,Mon May 11 03:18:03 UTC 2009,kindle2,vcu451,Reading my kindle2... Love it... Lee childs i...
1,4,5,Mon May 11 03:18:54 UTC 2009,kindle2,chadfu,"Ok, first assesment of the #kindle2 ...it fuck..."
2,4,6,Mon May 11 03:19:04 UTC 2009,kindle2,SIX15,@kenburbary You'll love your Kindle2. I've had...
3,4,7,Mon May 11 03:21:41 UTC 2009,kindle2,yamarama,@mikefish Fair enough. But i have the Kindle2...
4,4,8,Mon May 11 03:22:00 UTC 2009,kindle2,GeorgeVHulme,@richardebaker no. it is too big. I'm quite ha...

In [114]:
df_test.columns=['polarity of tweet','x','date of tweet','device','user_id','tweet_text']
df_test.head()

,polarity of tweet,x,date of tweet,device,user_id,tweet_text
0,4,4,Mon May 11 03:18:03 UTC 2009,kindle2,vcu451,Reading my kindle2... Love it... Lee childs i...
1,4,5,Mon May 11 03:18:54 UTC 2009,kindle2,chadfu,"Ok, first assesment of the #kindle2 ...it fuck..."
2,4,6,Mon May 11 03:19:04 UTC 2009,kindle2,SIX15,@kenburbary You'll love your Kindle2. I've had...
3,4,7,Mon May 11 03:21:41 UTC 2009,kindle2,yamarama,@mikefish Fair enough. But i have the Kindle2...
4,4,8,Mon May 11 03:22:00 UTC 2009,kindle2,GeorgeVHulme,@richardebaker no. it is too big. I'm quite ha...

In [115]:
df_test =df_test[['polarity of tweet','tweet_text']]
df_test.head()

   polarity of tweet                                         tweet_text
0                  4  Reading my kindle2...  Love it... Lee childs i...
1                  4  Ok, first assesment of the #kindle2 ...it fuck...
2                  4  @kenburbary You'll love your Kindle2. I've had...
3                  4  @mikefish  Fair enough. But i have the Kindle2...
4                  4  @richardebaker no. it is too big. I'm quite ha...

In [116]:
df_train= df[['polarity of tweet','tweet_text']]
df_train.head()

   polarity of tweet                                         tweet_text
0                  0  is upset that he can't update his Facebook by ...
1                  0  @Kenichan I dived many times for the ball. Man...
2                  0    my whole body feels itchy and like its on fire
3                  0  @nationwideclass no, it's not behaving at all....
4                  0                      @Kwesidei not the whole crew

In [117]:
# important feature to do classification target: noquery, variable :tweet_text
df =df_train.append(df_test)
df.head()

   polarity of tweet                                         tweet_text
0                  0  is upset that he can't update his Facebook by ...
1                  0  @Kenichan I dived many times for the ball. Man...
2                  0    my whole body feels itchy and like its on fire
3                  0  @nationwideclass no, it's not behaving at all....
4                  0                      @Kwesidei not the whole crew

In [118]:
# data statistics
neg = len(df[df["polarity of tweet"] == 0])
pos = len(df[df["polarity of tweet"] == 4])
neu = len(df[df["polarity of tweet"] == 2])
print (neg, neu, pos, len(df))

800176 139 800181 1600496

In [121]:
df.to_csv('D:/Assignment_ML/sentiment_tweet/processed_training_data.csv')

In [122]:
df['clean_tweet'] = df['tweet_text']
df.head(10)

,polarity of tweet,tweet_text,clean_tweet
0,0,is upset that he can't update his Facebook by ...,is upset that he can't update his Facebook by ...
1,0,@Kenichan I dived many times for the ball. Man...,@Kenichan I dived many times for the ball. Man...
2,0,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,"@nationwideclass no, it's not behaving at all....","@nationwideclass no, it's not behaving at all...."
4,0,@Kwesidei not the whole crew,@Kwesidei not the whole crew
5,0,Need a hug,Need a hug
6,0,@LOLTrish hey long time no see! Yes.. Rains a...,@LOLTrish hey long time no see! Yes.. Rains a...
7,0,@Tatiana_K nope they didn't have it,@Tatiana_K nope they didn't have it
8,0,@twittera que me muera ?,@twittera que me muera ?
9,0,spring break in plain city... it's snowing,spring break in plain city... it's snowing

In [123]:
#tweet cleaning process
#Step 1 : Removing "@user" from all the tweets
#Step 2 : Changing all the tweets into lowercase
#Step 3 : Apostrophe Lookup
#Step 4 : Short Word Lookup
#Step 5 : Emoticon Lookup
#Step 6 : Replacing Special Characters with space
#Step 7 : Replacing Numbers (integers) with space
#Step 8 : Removing words whom length is 1

#Step 1 : Removing "@user" from all the tweets
import re
def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for i in r:
        input_txt = re.sub(i, '', input_txt)
    return input_txt

In [124]:
df['clean_tweet'] = np.vectorize(remove_pattern)(df['clean_tweet'], "@[\w]*")

In [125]:
df.head()

,polarity of tweet,tweet_text,clean_tweet
0,0,is upset that he can't update his Facebook by ...,is upset that he can't update his Facebook by ...
1,0,@Kenichan I dived many times for the ball. Man...,I dived many times for the ball. Managed to s...
2,0,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,"@nationwideclass no, it's not behaving at all....","no, it's not behaving at all. i'm mad. why am..."
4,0,@Kwesidei not the whole crew,not the whole crew

In [126]:
#Step 2 : Changing all the tweets into lowercase
df['clean_tweet'] = df['clean_tweet'].apply(lambda x: x.lower())
df.head(10)

,polarity of tweet,tweet_text,clean_tweet
0,0,is upset that he can't update his Facebook by ...,is upset that he can't update his facebook by ...
1,0,@Kenichan I dived many times for the ball. Man...,i dived many times for the ball. managed to s...
2,0,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,"@nationwideclass no, it's not behaving at all....","no, it's not behaving at all. i'm mad. why am..."
4,0,@Kwesidei not the whole crew,not the whole crew
5,0,Need a hug,need a hug
6,0,@LOLTrish hey long time no see! Yes.. Rains a...,"hey long time no see! yes.. rains a bit ,onl..."
7,0,@Tatiana_K nope they didn't have it,nope they didn't have it
8,0,@twittera que me muera ?,que me muera ?
9,0,spring break in plain city... it's snowing,spring break in plain city... it's snowing

In [127]:
#Step 3 : Apostrophe Lookup
# Apostrophe Dictionary
apostrophe_dict = {
"ain't": "am not / are not",
"aren't": "are not / am not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he had / he would",
"he'd've": "he would have",
"he'll": "he shall / he will",
"he'll've": "he shall have / he will have",
"he's": "he has / he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how has / how is",
"i'd": "I had / I would",
"i'd've": "I would have",
"i'll": "I shall / I will",
"i'll've": "I shall have / I will have",
"i'm": "I am",
"i've": "I have",
"isn't": "is not",
"it'd": "it had / it would",
"it'd've": "it would have",
"it'll": "it shall / it will",
"it'll've": "it shall have / it will have",
"it's": "it has / it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she had / she would",
"she'd've": "she would have",
"she'll": "she shall / she will",
"she'll've": "she shall have / she will have",
"she's": "she has / she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as / so is",
"that'd": "that would / that had",
"that'd've": "that would have",
"that's": "that has / that is",
"there'd": "there had / there would",
"there'd've": "there would have",
"there's": "there has / there is",
"they'd": "they had / they would",
"they'd've": "they would have",
"they'll": "they shall / they will",
"they'll've": "they shall have / they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we had / we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what shall / what will",
"what'll've": "what shall have / what will have",
"what're": "what are",
"what's": "what has / what is",
"what've": "what have",
"when's": "when has / when is",
"when've": "when have",
"where'd": "where did",
"where's": "where has / where is",
"where've": "where have",
"who'll": "who shall / who will",
"who'll've": "who shall have / who will have",
"who's": "who has / who is",
"who've": "who have",
"why's": "why has / why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you had / you would",
"you'd've": "you would have",
"you'll": "you shall / you will",
"you'll've": "you shall have / you will have",
"you're": "you are",
"you've": "you have"
}
apostrophe_dict

{"'cause": 'because',
 "ain't": 'am not / are not',
 "aren't": 'are not / am not',
 "can't": 'cannot',
 "can't've": 'cannot have',
 "could've": 'could have',
 "couldn't": 'could not',
 "couldn't've": 'could not have',
 "didn't": 'did not',
 "doesn't": 'does not',
 "don't": 'do not',
 "hadn't": 'had not',
 "hadn't've": 'had not have',
 "hasn't": 'has not',
 "haven't": 'have not',
 "he'd": 'he had / he would',
 "he'd've": 'he would have',
 "he'll": 'he shall / he will',
 "he'll've": 'he shall have / he will have',
 "he's": 'he has / he is',
 "how'd": 'how did',
 "how'd'y": 'how do you',
 "how'll": 'how will',
 "how's": 'how has / how is',
 "i'd": 'I had / I would',
 "i'd've": 'I would have',
 "i'll": 'I shall / I will',
 "i'll've": 'I shall have / I will have',
 "i'm": 'I am',
 "i've": 'I have',
 "isn't": 'is not',
 "it'd": 'it had / it would',
 "it'd've": 'it would have',
 "it'll": 'it shall / it will',
 "it'll've": 'it shall have / it will have',
 "it's": 'it has / it is',
 "let's": 'let us',
 "ma'am": 'madam',
 "mayn't": 'may not',
 "might've": 'might have',
 "mightn't": 'might not',
 "mightn't've": 'might not have',
 "must've": 'must have',
 "mustn't": 'must not',
 "mustn't've": 'must not have',
 "needn't": 'need not',
 "needn't've": 'need not have',
 "o'clock": 'of the clock',
 "oughtn't": 'ought not',
 "oughtn't've": 'ought not have',
 "sha'n't": 'shall not',
 "shan't": 'shall not',
 "shan't've": 'shall not have',
 "she'd": 'she had / she would',
 "she'd've": 'she would have',
 "she'll": 'she shall / she will',
 "she'll've": 'she shall have / she will have',
 "she's": 'she has / she is',
 "should've": 'should have',
 "shouldn't": 'should not',
 "shouldn't've": 'should not have',
 "so's": 'so as / so is',
 "so've": 'so have',
 "that'd": 'that would / that had',
 "that'd've": 'that would have',
 "that's": 'that has / that is',
 "there'd": 'there had / there would',
 "there'd've": 'there would have',
 "there's": 'there has / there is',
 "they'd": 'they had / they would',
 "they'd've": 'they would have',
 "they'll": 'they shall / they will',
 "they'll've": 'they shall have / they will have',
 "they're": 'they are',
 "they've": 'they have',
 "to've": 'to have',
 "wasn't": 'was not',
 "we'd": 'we had / we would',
 "we'd've": 'we would have',
 "we'll": 'we will',
 "we'll've": 'we will have',
 "we're": 'we are',
 "we've": 'we have',
 "weren't": 'were not',
 "what'll": 'what shall / what will',
 "what'll've": 'what shall have / what will have',
 "what're": 'what are',
 "what's": 'what has / what is',
 "what've": 'what have',
 "when's": 'when has / when is',
 "when've": 'when have',
 "where'd": 'where did',
 "where's": 'where has / where is',
 "where've": 'where have',
 "who'll": 'who shall / who will',
 "who'll've": 'who shall have / who will have',
 "who's": 'who has / who is',
 "who've": 'who have',
 "why's": 'why has / why is',
 "why've": 'why have',
 "will've": 'will have',
 "won't": 'will not',
 "won't've": 'will not have',
 "would've": 'would have',
 "wouldn't": 'would not',
 "wouldn't've": 'would not have',
 "y'all": 'you all',
 "y'all'd": 'you all would',
 "y'all'd've": 'you all would have',
 "y'all're": 'you all are',
 "y'all've": 'you all have',
 "you'd": 'you had / you would',
 "you'd've": 'you would have',
 "you'll": 'you shall / you will',
 "you'll've": 'you shall have / you will have',
 "you're": 'you are',
 "you've": 'you have'}

In [128]:
def lookup_dict(text, dictionary):
    for word in text.split():
        if word.lower() in dictionary:
            if word.lower() in text.split():
                text = text.replace(word, dictionary[word.lower()])
    return text

In [129]:
df['clean_tweet'] = df['clean_tweet'].apply(lambda x: lookup_dict(x,apostrophe_dict))
df.head(10)

,polarity of tweet,tweet_text,clean_tweet
0,0,is upset that he can't update his Facebook by ...,is upset that he cannot update his facebook by...
1,0,@Kenichan I dived many times for the ball. Man...,i dived many times for the ball. managed to s...
2,0,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,"@nationwideclass no, it's not behaving at all....","no, it has / it is not behaving at all. I am ..."
4,0,@Kwesidei not the whole crew,not the whole crew
5,0,Need a hug,need a hug
6,0,@LOLTrish hey long time no see! Yes.. Rains a...,"hey long time no see! yes.. rains a bit ,onl..."
7,0,@Tatiana_K nope they didn't have it,nope they did not have it
8,0,@twittera que me muera ?,que me muera ?
9,0,spring break in plain city... it's snowing,spring break in plain city... it has / it is s...

In [130]:
#Step 4 : Short Word Lookup
short_word_dict = {
"121": "one to one",
"a/s/l": "age, sex, location",
"adn": "any day now",
"afaik": "as far as I know",
"afk": "away from keyboard",
"aight": "alright",
"alol": "actually laughing out loud",
"b4": "before",
"b4n": "bye for now",
"bak": "back at the keyboard",
"bf": "boyfriend",
"bff": "best friends forever",
"bfn": "bye for now",
"bg": "big grin",
"bta": "but then again",
"btw": "by the way",
"cid": "crying in disgrace",
"cnp": "continued in my next post",
"cp": "chat post",
"cu": "see you",
"cul": "see you later",
"cul8r": "see you later",
"cya": "bye",
"cyo": "see you online",
"dbau": "doing business as usual",
"fud": "fear, uncertainty, and doubt",
"fwiw": "for what it's worth",
"fyi": "for your information",
"g": "grin",
"g2g": "got to go",
"ga": "go ahead",
"gal": "get a life",
"gf": "girlfriend",
"gfn": "gone for now",
"gmbo": "giggling my butt off",
"gmta": "great minds think alike",
"h8": "hate",
"hagn": "have a good night",
"hdop": "help delete online predators",
"hhis": "hanging head in shame",
"iac": "in any case",
"ianal": "I am not a lawyer",
"ic": "I see",
"idk": "I don't know",
"imao": "in my arrogant opinion",
"imnsho": "in my not so humble opinion",
"imo": "in my opinion",
"iow": "in other words",
"ipn": "I’m posting naked",
"irl": "in real life",
"jk": "just kidding",
"l8r": "later",
"ld": "later, dude",
"ldr": "long distance relationship",
"llta": "lots and lots of thunderous applause",
"lmao": "laugh my ass off",
"lmirl": "let's meet in real life",
"lol": "laugh out loud",
"ltr": "longterm relationship",
"lulab": "love you like a brother",
"lulas": "love you like a sister",
"luv": "love",
"m/f": "male or female",
"m8": "mate",
"milf": "mother I would like to fuck",
"oll": "online love",
"omg": "oh my god",
"otoh": "on the other hand",
"pir": "parent in room",
"ppl": "people",
"r": "are",
"rofl": "roll on the floor laughing",
"rpg": "role playing games",
"ru": "are you",
"shid": "slaps head in disgust",
"somy": "sick of me yet",
"sot": "short of time",
"thanx": "thanks",
"thx": "thanks",
"ttyl": "talk to you later",
"u": "you",
"ur": "you are",
"uw": "you’re welcome",
"wb": "welcome back",
"wfm": "works for me",
"wibni": "wouldn't it be nice if",
"wtf": "what the fuck",
"wtg": "way to go",
"wtgp": "want to go private",
"ym": "young man",
"gr8": "great"
}
short_word_dict

{'121': 'one to one',
 'a/s/l': 'age, sex, location',
 'adn': 'any day now',
 'afaik': 'as far as I know',
 'afk': 'away from keyboard',
 'aight': 'alright',
 'alol': 'actually laughing out loud',
 'b4': 'before',
 'b4n': 'bye for now',
 'bak': 'back at the keyboard',
 'bf': 'boyfriend',
 'bff': 'best friends forever',
 'bfn': 'bye for now',
 'bg': 'big grin',
 'bta': 'but then again',
 'btw': 'by the way',
 'cid': 'crying in disgrace',
 'cnp': 'continued in my next post',
 'cp': 'chat post',
 'cu': 'see you',
 'cul': 'see you later',
 'cul8r': 'see you later',
 'cya': 'bye',
 'cyo': 'see you online',
 'dbau': 'doing business as usual',
 'fud': 'fear, uncertainty, and doubt',
 'fwiw': "for what it's worth",
 'fyi': 'for your information',
 'g': 'grin',
 'g2g': 'got to go',
 'ga': 'go ahead',
 'gal': 'get a life',
 'gf': 'girlfriend',
 'gfn': 'gone for now',
 'gmbo': 'giggling my butt off',
 'gmta': 'great minds think alike',
 'gr8': 'great',
 'h8': 'hate',
 'hagn': 'have a good night',
 'hdop': 'help delete online predators',
 'hhis': 'hanging head in shame',
 'iac': 'in any case',
 'ianal': 'I am not a lawyer',
 'ic': 'I see',
 'idk': "I don't know",
 'imao': 'in my arrogant opinion',
 'imnsho': 'in my not so humble opinion',
 'imo': 'in my opinion',
 'iow': 'in other words',
 'ipn': 'I’m posting naked',
 'irl': 'in real life',
 'jk': 'just kidding',
 'l8r': 'later',
 'ld': 'later, dude',
 'ldr': 'long distance relationship',
 'llta': 'lots and lots of thunderous applause',
 'lmao': 'laugh my ass off',
 'lmirl': "let's meet in real life",
 'lol': 'laugh out loud',
 'ltr': 'longterm relationship',
 'lulab': 'love you like a brother',
 'lulas': 'love you like a sister',
 'luv': 'love',
 'm/f': 'male or female',
 'm8': 'mate',
 'milf': 'mother I would like to fuck',
 'oll': 'online love',
 'omg': 'oh my god',
 'otoh': 'on the other hand',
 'pir': 'parent in room',
 'ppl': 'people',
 'r': 'are',
 'rofl': 'roll on the floor laughing',
 'rpg': 'role playing games',
 'ru': 'are you',
 'shid': 'slaps head in disgust',
 'somy': 'sick of me yet',
 'sot': 'short of time',
 'thanx': 'thanks',
 'thx': 'thanks',
 'ttyl': 'talk to you later',
 'u': 'you',
 'ur': 'you are',
 'uw': 'you’re welcome',
 'wb': 'welcome back',
 'wfm': 'works for me',
 'wibni': "wouldn't it be nice if",
 'wtf': 'what the fuck',
 'wtg': 'way to go',
 'wtgp': 'want to go private',
 'ym': 'young man'}

In [131]:
df['clean_tweet'] = df['clean_tweet'].apply(lambda x: lookup_dict(x,short_word_dict))
df.head(10)

,polarity of tweet,tweet_text,clean_tweet
0,0,is upset that he can't update his Facebook by ...,is upset that he cannot update his facebook by...
1,0,@Kenichan I dived many times for the ball. Man...,i dived many times for the ball. managed to s...
2,0,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,"@nationwideclass no, it's not behaving at all....","no, it has / it is not behaving at all. I am ..."
4,0,@Kwesidei not the whole crew,not the whole crew
5,0,Need a hug,need a hug
6,0,@LOLTrish hey long time no see! Yes.. Rains a...,"hey long time no see! yes.. rains a bit ,onl..."
7,0,@Tatiana_K nope they didn't have it,nope they did not have it
8,0,@twittera que me muera ?,que me muera ?
9,0,spring break in plain city... it's snowing,spring break in plain city... it has / it is s...

In [132]:
#Step 5 : Emoticon Lookup
emoticon_dict = {
":)": "happy",
":‑)": "happy",
":-]": "happy",
":-3": "happy",
":->": "happy",
"8-)": "happy",
":-}": "happy",
":o)": "happy",
":c)": "happy",
":^)": "happy",
"=]": "happy",
"=)": "happy",
"<3": "happy",
":-(": "sad",
":(": "sad",
":c": "sad",
":<": "sad",
":[": "sad",
">:[": "sad",
":{": "sad",
">:(": "sad",
":-c": "sad",
":-< ": "sad",
":-[": "sad",
":-||": "sad"
}
emoticon_dict

{'8-)': 'happy',
 ':(': 'sad',
 ':)': 'happy',
 ':-(': 'sad',
 ':-3': 'happy',
 ':-< ': 'sad',
 ':->': 'happy',
 ':-[': 'sad',
 ':-]': 'happy',
 ':-c': 'sad',
 ':-||': 'sad',
 ':-}': 'happy',
 ':<': 'sad',
 ':[': 'sad',
 ':^)': 'happy',
 ':c': 'sad',
 ':c)': 'happy',
 ':o)': 'happy',
 ':{': 'sad',
 ':‑)': 'happy',
 '<3': 'happy',
 '=)': 'happy',
 '=]': 'happy',
 '>:(': 'sad',
 '>:[': 'sad'}

In [133]:
df['clean_tweet'] = df['clean_tweet'].apply(lambda x: lookup_dict(x,emoticon_dict))
df.head(10)

,polarity of tweet,tweet_text,clean_tweet
0,0,is upset that he can't update his Facebook by ...,is upset that he cannot update his facebook by...
1,0,@Kenichan I dived many times for the ball. Man...,i dived many times for the ball. managed to s...
2,0,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,"@nationwideclass no, it's not behaving at all....","no, it has / it is not behaving at all. I am ..."
4,0,@Kwesidei not the whole crew,not the whole crew
5,0,Need a hug,need a hug
6,0,@LOLTrish hey long time no see! Yes.. Rains a...,"hey long time no see! yes.. rains a bit ,onl..."
7,0,@Tatiana_K nope they didn't have it,nope they did not have it
8,0,@twittera que me muera ?,que me muera ?
9,0,spring break in plain city... it's snowing,spring break in plain city... it has / it is s...

In [134]:
#Step 6 : Replacing Special Characters with space
df['clean_tweet'] = df['clean_tweet'].apply(lambda x: re.sub(r'[^\w\s]',' ',x))
df.head(10)

,polarity of tweet,tweet_text,clean_tweet
0,0,is upset that he can't update his Facebook by ...,is upset that he cannot update his facebook by...
1,0,@Kenichan I dived many times for the ball. Man...,i dived many times for the ball managed to s...
2,0,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,"@nationwideclass no, it's not behaving at all....",no it has it is not behaving at all I am ...
4,0,@Kwesidei not the whole crew,not the whole crew
5,0,Need a hug,need a hug
6,0,@LOLTrish hey long time no see! Yes.. Rains a...,hey long time no see yes rains a bit onl...
7,0,@Tatiana_K nope they didn't have it,nope they did not have it
8,0,@twittera que me muera ?,que me muera
9,0,spring break in plain city... it's snowing,spring break in plain city it has it is s...

In [135]:
#Step 7 : Replacing Numbers (integers) with space
df['clean_tweet'] = df['clean_tweet'].apply(lambda x: re.sub(r'[^a-zA-Z0-9]',' ',x))
df.head(10)

,polarity of tweet,tweet_text,clean_tweet
0,0,is upset that he can't update his Facebook by ...,is upset that he cannot update his facebook by...
1,0,@Kenichan I dived many times for the ball. Man...,i dived many times for the ball managed to s...
2,0,my whole body feels itchy and like its on fire,my whole body feels itchy and like its on fire
3,0,"@nationwideclass no, it's not behaving at all....",no it has it is not behaving at all I am ...
4,0,@Kwesidei not the whole crew,not the whole crew
5,0,Need a hug,need a hug
6,0,@LOLTrish hey long time no see! Yes.. Rains a...,hey long time no see yes rains a bit onl...
7,0,@Tatiana_K nope they didn't have it,nope they did not have it
8,0,@twittera que me muera ?,que me muera
9,0,spring break in plain city... it's snowing,spring break in plain city it has it is s...

In [136]:
#Step 8 : Removing words whom length is 1
df['clean_tweet'] = df['clean_tweet'].apply(lambda x: ' '.join([w for w in x.split() if len(w)>1]))
df['clean_tweet'][0:10]

0    is upset that he cannot update his facebook by...
1    dived many times for the ball managed to save ...
2       my whole body feels itchy and like its on fire
3    no it has it is not behaving at all am mad why...
4                                   not the whole crew
5                                             need hug
6    hey long time no see yes rains bit only bit la...
7                            nope they did not have it
8                                         que me muera
9      spring break in plain city it has it is snowing
Name: clean_tweet, dtype: object

In [138]:
df.to_csv('D:/Assignment_ML/sentiment_tweet/processed_training_data_preprocessed.csv')